### ISSUE TITLE
Exported file doesn't seem to be well-formatted

### ISSUE THREAD

**Issue by stephane-ruhlmann** [rikkertkoppes/json2xls#3]
Hi,

All seems to be good when exporting some json to an xlsx : Excel successfully opens the file and it's how it's supposed to be.
However if I try to import the exported file (tested with modules 'xlsx-to-json' and 'excel'), file appears to be empty.
If I open the file with Excel and save it, it will work perfectly.
Any idea ?

**Comment by rikkertkoppes** [comment]
This would be out of scope for this project, since it uses [node-excel-export](https://github.com/functionscope/Node-Excel-Export) as a dependency

You might want to test and raise the issue there. In any case, I will update the dependency to see if [this change](https://github.com/functionscope/Node-Excel-Export/commit/0fb61a5ad3f4bd8180b2c548faba5aa6e7416c52) perhaps solved the problem

**Comment by stephane-ruhlmann** [comment]
Will try it, thanks!

**Comment by duanefields** [comment]
Doesn't work importing the file into Mac's Numbers.app either
